/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : CCNT1.H
**     Project   : SenCos
**     Processor : 56F8367
**     Component : DSP_CycleCounter
**     Version   : Component 01.005, Driver 01.05, CPU db: 2.87.058
**     Compiler  : Metrowerks DSP C Compiler
**     Date/Time : 26/04/2010, 12:35 a.m.
**     Abstract  :
**          This bean provide Cycle Count Services support and services.
**     Settings  :
**          Cycle counter uses DSP_FreeCntr timer
**     Contents  :
**         cycleCountCalibrate - void CCNT1_cycleCountCalibrate(void);
**         cycleCountReport    - void CCNT1_cycleCountReport(long *pExecTime, int n);
**         cycleCountStart     - void CCNT1_cycleCountStart(void);
**         cycleCountStop      - UWord32 CCNT1_cycleCountStop(void);
**
**     (c) Freescale Semiconductor
**     2004 All Rights Reserved
**
**     Copyright : 1997 - 2009 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef __CCNT1
#define __CCNT1

/* MODULE CCNT1. */

/*Include shared modules, which are used for whole project*/
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited beans */
#include "Inhr1.h"
#include "cyclecount.h"

#include "Cpu.h"



/*
void CCNT1_cycleCountCalibrate(void);
*/
#define CCNT1_cycleCountCalibrate(void) cycleCountCalibrate(void)
/*
** ===================================================================
**     Method      :  CCNT1_cycleCountCalibrate (component DSP_CycleCounter)
**
**     Description :
**         The cycleCountCalibrate function determines how many
**         system clock cycles are required to execute the
**         cycleCountStart() and cycleCountStop() functions. This
**         value will be used by the cycleCountStop() function in
**         order to subtract out the cycles that are not part of the
**         user’s code being measured.
**         Please note: If your program is running in a 'FLASH'
**         memory, call the cycleCountCalibrate function immediately
**         before the cycleCountStart function.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

/*
void CCNT1_cycleCountReport(long *pExecTime,int n);
*/
#define CCNT1_cycleCountReport(pExecTime,n) cycleCountReport(pExecTime,n)
/*
** ===================================================================
**     Method      :  CCNT1_cycleCountReport (component DSP_CycleCounter)
**
**     Description :
**         The cycleCountReport function calculates the mean,
**         maximum, and minimum execution times, and writes the
**         results to the Console.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pExecTime       - Pointer to an array of
**                           measured execution times
**         n               - Length of pExecTime (number of valid
**                           execution times in pExecTime)
**     Returns     : Nothing
** ===================================================================
*/

/*
void CCNT1_cycleCountStart(void);
*/
#define CCNT1_cycleCountStart(void) cycleCountStart(void)
/*
** ===================================================================
**     Method      :  CCNT1_cycleCountStart (component DSP_CycleCounter)
**
**     Description :
**         The cycleCountStart() function performs the
**         initialization of the Quad Timers and enables counting of
**         system clock cycles.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

/*
UWord32 CCNT1_cycleCountStop(void);
*/
#define CCNT1_cycleCountStop(void) cycleCountStop(void)
/*
** ===================================================================
**     Method      :  CCNT1_cycleCountStop (component DSP_CycleCounter)
**
**     Description :
**         The cycleCountStop() function disables the Quad Timers
**         and returns the number of system clock cycles counted by
**         Quad Timers. Note that cycleCountStart() must be called
**         prior to getting another cycle count value, since
**         cycleCountStop() disables the timers.
**     Parameters  : None
**     Returns     :
**         ---             - Number of system clock cycles since
**                           cycleCountStart was called, minus the
**                           Calibration value.
** ===================================================================
*/

/* END CCNT1. */

#endif /* ifndef __CCNT1 */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.00 [04.35]
**     for the Freescale 56800 series of microcontrollers.
**
** ###################################################################
*/
