/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : Inhr1.C
**     Project   : SenCos
**     Processor : 56F8367
**     Component : FreeCntr
**     Version   : Component 01.112, Driver 02.04, CPU db: 2.87.058
**     Compiler  : Metrowerks DSP C Compiler
**     Date/Time : 26/04/2010, 12:35 a.m.
**     Abstract  :
**         This device "FreeCntr" implements a free running counter for
**         time measurement.
**     Settings  :
**         Timer name                  : TMRC01 (32-bit)
**         Counter shared              : No
**
**         High speed mode
**             Prescaler               : divide-by-1
**             Clock                   : 60000000 Hz
**           Period
**             Xtal ticks              : 572662306
**             microseconds            : 71582788
**             milliseconds            : 71583
**             seconds                 : 72
**             seconds (real)          : 71.582788266667
**           Frequency of counting (Bus clock / prescaler)
**             Hz                      : 60000000
**
**         Initialization:
**              Timer                  : Enabled
**
**         Timer registers
**              Counter                : TMRC1_CNTR [61653]
**              Mode                   : TMRC1_CTRL [61654]
**              Run                    : TMRC1_CTRL [61654]
**              Prescaler              : TMRC1_CTRL [61654]
**
**         User handling procedure     : not specified
**     Contents  :
**         Enable          - byte Inhr1_Enable(void);
**         Disable         - byte Inhr1_Disable(void);
**         Reset           - byte Inhr1_Reset(void);
**         GetCounterValue - byte Inhr1_GetCounterValue(Inhr1_TTimerValue *Value);
**
**     Copyright : 1997 - 2009 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE Inhr1. */

#include "Inhr1.h"

static bool EnUser;                    /* Enable/Disable device by user */

/* Internal method prototypes */
static void HWEnDi(void);
static void SetPV(byte Val);

/*
** ===================================================================
**     Method      :  SetPV (component FreeCntr)
**
**     Description :
**         Sets prescaler value. The method is called automatically as a 
**         part of several internal methods.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static void SetPV(byte Val)
{
  EnterCritical();                     /* Disable global interrupts */
  setRegBitGroup(TMRC0_CTRL,PCS,Val);  /* Store given value to the prescaler */
  setReg(TMRC0_CNTR,0);                /* Reset counter */
  setReg(TMRC1_CNTR,0);
  ExitCritical();                      /* Enable global interrupts */
}

/*
** ===================================================================
**     Method      :  HWEnDi (component FreeCntr)
**
**     Description :
**         Enables or disables the peripheral(s) associated with the bean.
**         The method is called automatically as a part of the Enable and 
**         Disable methods and several internal methods.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static void HWEnDi(void)
{
  if (EnUser) {                        /* Enable device? */
    setReg(TMRC0_CNTR,0);              /* Reset counter */
    setReg(TMRC1_CNTR,0);
    setRegBitGroup(TMRC0_CTRL,CM,1);   /* Run counter */
  }
  else {                               /* Disable device? */
    setRegBitGroup(TMRC0_CTRL,CM,0);   /* Stop counter */
  }
}

/*
** ===================================================================
**     Method      :  Inhr1_Enable (component FreeCntr)
**
**     Description :
**         This method enables the component, i.e. timer is enabled and
**         the internal clocks are counted. The method usually also
**         reset the counter (if it is supported by HW). 
**         The method is not available if the counter is shared.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte Inhr1_Enable(void)
{
  if (!EnUser) {                       /* Is the device disabled by user? */
    EnUser = TRUE;                     /* If yes then set the flag "device enabled" */
    HWEnDi();                          /* Enable the device */
  }
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  Inhr1_Disable (component FreeCntr)
**
**     Description :
**         This method disables the component, i.e. timer is disabled
**         and the internal clocks are stopped. Last counter value is
**         usually preserved in the counter (if it is supported by HW).
**         The method is not available if the counter is shared.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte Inhr1_Disable(void)
{
  if (EnUser) {                        /* Is the device enabled by user? */
    EnUser = FALSE;                    /* If yes then set the flag "device disabled" */
    HWEnDi();                          /* Disable the device */
  }
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  Inhr1_Reset (component FreeCntr)
**
**     Description :
**         This method resets the timer-counter (sets to zero for
**         up-counting HW or to appropriate value for down-counting HW).
**         The method is available only if the counter register can be
**         set by software and the counter is not shared.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte Inhr1_Reset(void)
{
  EnterCritical();                     /* Disable global interrupts */
  setReg(TMRC0_CNTR,0);                /* Reset counter register */
  setReg(TMRC1_CNTR,0);
  ExitCritical();                      /* Enable global interrupts */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  Inhr1_GetCounterValue (component FreeCntr)
**
**     Description :
**         This method returns a content of counter.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Value           - A pointer to the returned 32-bit value.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte Inhr1_GetCounterValue(Inhr1_TTimerValue *Value)
{
  *Value = getReg(TMRC0_CNTR);         /* Get lower part */
  *Value += ((dword)getReg(TMRC1_HOLD) << 16); /* Add higher part */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  Inhr1_Init (component FreeCntr)
**
**     Description :
**         Initializes the associated peripheral(s) and the beans 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void Inhr1_Init(void)
{
  /* TMRC0_CTRL: CM=0,PCS=0,SCS=0,ONCE=0,LENGTH=0,DIR=0,Co_INIT=0,OM=0 */
  setReg(TMRC0_CTRL,0);                /* Stop all functions of the timer */
  /* TMRC1_CTRL: CM=7,PCS=4,SCS=0,ONCE=0,LENGTH=0,DIR=0,Co_INIT=0,OM=0 */
  setReg(TMRC1_CTRL,59392);            /* Set up cascade counter mode */
  setReg(TMRC1_CNTR,0);                /* Reset counter register */
  setReg(TMRC0_CNTR,0);
  setReg(TMRC1_LOAD,0);                /* Reset load register */
  setReg(TMRC0_LOAD,0);
  setReg(TMRC0_CMP1,65535);            /* Set up compare 1 register to maximum */
  EnUser = TRUE;                       /* Enable device */
  SetPV((byte)8);                      /* Set prescaler register according to the selected high speed CPU mode */
  HWEnDi();                            /* Enable/disable device according to status flags */
}

/* END Inhr1. */

/*
** ###################################################################
**
**     This file was created by Processor Expert 3.00 [04.35]
**     for the Freescale 56800 series of microcontrollers.
**
** ###################################################################
*/
