/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : AFR1.H
**     Project   : TP1
**     Processor : 56F8367
**     Component : DSP_Func_AFR
**     Version   : Component 01.029, Driver 01.05, CPU db: 2.87.058
**     Compiler  : Metrowerks DSP C Compiler
**     Date/Time : 30/07/2015, 19:47
**     Abstract  :
**          This bean implements many functions for single-dimensioned arrays
**          of fractional types as library routines. Most basic math primitives,
**          such as add, multiply, and subtract, have corresponding array
**          operations. The array operations provide highly optimized loops
**          on the elements of each array to provide the best performance.
**     Settings  :
**          Bean Name                      : AFR1
**          Use Assembler Files            : yes
**          Basic Fractional Math Library  : MFR1
**     Contents  :
**         afr16Abs     - void AFR1_afr16Abs(Frac16 *pX, Frac16 *pZ, UInt16 n);
**         afr16Add     - void AFR1_afr16Add(Frac16 *pX, Frac16 *pY, Frac16 *pZ, UInt16 n);
**         afr16Div     - void AFR1_afr16Div(Frac16 *pX, Frac16 *pY, Frac16 *pZ, UInt16 n);
**         afr16Equal   - bool AFR1_afr16Equal(Frac16 *pX, Frac16 *pY, UInt16 n);
**         afr16Mac_r   - void AFR1_afr16Mac_r(Frac16 *pW, Frac16 *pX, Frac16 *pY, Frac16 *pZ, UInt16 n);
**         afr16Max     - Frac16 AFR1_afr16Max(Frac16 *pX, UInt16 n, UInt16 *pMaxIndex);
**         afr16Msu_r   - void AFR1_afr16Msu_r(Frac16 *pW, Frac16 *pX, Frac16 *pY, Frac16 *pZ, UInt16 n);
**         afr16Min     - Frac16 AFR1_afr16Min(Frac16 *pX, UInt16 n, UInt16 *pMinIndex);
**         afr16Mult    - void AFR1_afr16Mult(Frac16 *pX, Frac16 *pY, Frac16 *pZ, UInt16 n);
**         afr16Mult_r  - void AFR1_afr16Mult_r(Frac16 *pX, Frac16 *pY, Frac16 *pZ, UInt16 n);
**         afr16Negate  - void AFR1_afr16Negate(Frac16 *pX, Frac16 *pZ, UInt16 n);
**         afr16Rand    - void AFR1_afr16Rand(Frac16 *pZ, UInt16 n);
**         afr16Sqrt    - void AFR1_afr16Sqrt(Frac16 *pX, Frac16 *pZ, UInt16 n);
**         afr16Sub     - void AFR1_afr16Sub(Frac16 *pX, Frac16 *pY, Frac16 *pZ, UInt16 n);
**         afr32Abs     - void AFR1_afr32Abs(Frac32 *pX, Frac32 *pZ, UInt16 n);
**         afr32Add     - void AFR1_afr32Add(Frac32 *pX, Frac32 *pY, Frac32 *pZ, UInt16 n);
**         afr32Div     - void AFR1_afr32Div(Frac32 *pX, Frac16 *pY, Frac16 *pZ, UInt16 n);
**         afr32Equal   - bool AFR1_afr32Equal(Frac32 *pX, Frac32 *pY, UInt16 n);
**         afr32Mac     - void AFR1_afr32Mac(Frac32 *pW, Frac16 *pX, Frac16 *pY, Frac32 *pZ, UInt16 n);
**         afr32Mac_r   - void AFR1_afr32Mac_r(Frac32 *pW, Frac16 *pX, Frac16 *pY, Frac16 *pZ, UInt16 n);
**         afr32Max     - Frac32 AFR1_afr32Max(Frac32 *pX, UInt16 n, UInt16 *pMaxIndex);
**         afr32Min     - Frac32 AFR1_afr32Min(Frac32 *pX, UInt16 n, UInt16 *pMinIndex);
**         afr32Msu     - void AFR1_afr32Msu(Frac32 *pW, Frac16 *pX, Frac16 *pY, Frac32 *pZ, UInt16 n);
**         afr32Msu_r   - void AFR1_afr32Msu_r(Frac32 *pW, Frac16 *pX, Frac16 *pY, Frac16 *pZ, UInt16 n);
**         afr32Mult    - void AFR1_afr32Mult(Frac16 *pX, Frac16 *pY, Frac32 *pZ, UInt16 n);
**         afr32Negate  - void AFR1_afr32Negate(Frac32 *pX, Frac32 *pZ, UInt16 n);
**         afr32Mult_ls - void AFR1_afr32Mult_ls(Frac32 *pX, Frac16 *pY, Frac32 *pZ, UInt16 n);
**         afr32Round   - void AFR1_afr32Round(Frac32 *pX, Frac16 *pZ, UInt16 n);
**         afr32Sqrt    - void AFR1_afr32Sqrt(Frac32 *pX, Frac16 *pZ, UInt16 n);
**         afr32Sub     - void AFR1_afr32Sub(Frac32 *pX, Frac32 *pY, Frac32 *pZ, UInt16 n);
**
**     (c) Freescale Semiconductor
**     2004 All Rights Reserved
**
**     Copyright : 1997 - 2009 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef __AFR1
#define __AFR1

/* MODULE AFR1. */

/*Include shared modules, which are used for whole project*/
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited beans */
#include "MFR1.h"
#include "port.h"
#include "dspfunc.h"

#include "Cpu.h"



#define AFR1_afr16Abs(pX,pZ,n) afr16Abs(pX,pZ,n)
void afr16Abs(Frac16 *pX,Frac16 *pZ,UInt16 n);
/*
** ===================================================================
**     Method      :  AFR1_afr16Abs (component DSP_Func_AFR)
**
**     Description :
**         The function calculates the absolute value of each
**         fractional element of the input array pointed to by pX; i.e.,
**         pZ[i] = pX[i], 0 <= i < n. This method cannot be disabled if
**         Use Assembler Files property is enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pX              - Pointer to an input array of fractional data
**                           values.
**       * pZ              - Pointer to an output array of fractional
**                           data values.
**         n               - The length of the input and output arrays.
**     Returns     : Nothing
** ===================================================================
*/

#define AFR1_afr16Add(pX,pY,pZ,n) afr16Add(pX,pY,pZ,n)
void afr16Add(Frac16 *pX,Frac16 *pY,Frac16 *pZ,UInt16 n);
/*
** ===================================================================
**     Method      :  AFR1_afr16Add (component DSP_Func_AFR)
**
**     Description :
**         The function totals the corresponding elements of each input
**         array; i.e., pZ[i] = pX[i] + pY[i], 0 <= i < n. This method
**         cannot be disabled if Use Assembler Files property is
**         enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pX              - Pointer to the first input array of
**                           fractional data values.
**       * pY              - Pointer to the second input array of
**                           fractional data values.
**       * pZ              - Pointer to the output array of fractional
**                           results.
**         n               - The length of all input and output arrays.
**     Returns     : Nothing
** ===================================================================
*/

#define AFR1_afr16Div(pX,pY,pZ,n) afr16Div(pX,pY,pZ,n)
void afr16Div(Frac16 *pX,Frac16 *pY,Frac16 *pZ,UInt16 n);
/*
** ===================================================================
**     Method      :  AFR1_afr16Div (component DSP_Func_AFR)
**
**     Description :
**         The function divides the corresponding elements of each
**         input array; i.e., pZ[i] = pX[i] / pY[i], 0 <= i < n. In
**         this equation, pX[i] and pY[i] must be positive, and pY[i]
**         must be greater than or equal to pX[i]. This method cannot
**         be disabled if Use Assembler Files property is enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pX              - Pointer to the input array of dividends.
**       * pY              - Pointer to the input array of divisors.
**       * pZ              - Pointer to the output array of quotients.
**         n               - The length of all input and output arrays.
**     Returns     : Nothing
** ===================================================================
*/

#define AFR1_afr16Equal(pX,pY,n) afr16Equal(pX,pY,n)
bool afr16Equal(Frac16 *pX,Frac16 *pY,UInt16 n);
/*
** ===================================================================
**     Method      :  AFR1_afr16Equal (component DSP_Func_AFR)
**
**     Description :
**         The function compares the corresponding elements of each
**         fractional array for equality, i.e., pX[i] == pY[i], 0 <= i
**         < n. This method cannot be disabled if Use Assembler Files
**         property is enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pX              - Pointer to an input array of fractional data
**                           values.
**       * pY              - Pointer to an input array of fractional data
**                           values.
**         n               - The length of both input arrays.
**     Returns     :
**         ---             - The function returns true if all
**                           corresponding elements of the two input
**                           arrays are equal. If any element of the two
**                           input arrays is not equal, equal returns
**                           false.
** ===================================================================
*/

#define AFR1_afr16Mac_r(pW,pX,pY,pZ,n) afr16Mac_r(pW,pX,pY,pZ,n)
void afr16Mac_r(Frac16 *pW,Frac16 *pX,Frac16 *pY,Frac16 *pZ,UInt16 n);
/*
** ===================================================================
**     Method      :  AFR1_afr16Mac_r (component DSP_Func_AFR)
**
**     Description :
**         The function multiplies the corresponding elements of each X
**         and Y input array and adds the result to the corresponding
**         element of the W input array; i.e., pZ[i] = (pX[i] * pY[i])
**         + pW[i], 0 <= i < n. This method cannot be disabled if Use
**         Assembler Files property is enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pW              - Pointer to the input array of fractional
**                           data values to be added.
**       * pX              - Pointer to the input array of fractional
**                           data values to be multiplied.
**       * pY              - Pointer to the input array of fractional
**                           data values to be multiplied.
**       * pZ              - Pointer to the output array.
**         n               - The length of all input and output arrays.
**     Returns     : Nothing
** ===================================================================
*/

#define AFR1_afr16Max(pX,n,pMaxIndex) afr16Max(pX,n,pMaxIndex)
Frac16 afr16Max(Frac16 *pX,UInt16 n,UInt16 *pMaxIndex);
/*
** ===================================================================
**     Method      :  AFR1_afr16Max (component DSP_Func_AFR)
**
**     Description :
**         The function searches the input array for the maximum
**         fractional value. This method cannot be disabled if Use
**         Assembler Files property is enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pX              - Pointer to the input array of fractional
**                           data values.
**         n               - The length of the array.
**       * pMaxIndex       - A pointer to a variable in
**                           which to store the index of the maximum
**                           value of the input array; may be NULL.
**     Returns     :
**         ---             - The function returns the value of the
**                           maximum array element as the return value
**                           of the function. In addition, the array
**                           index of the maximum array element may be
**                           stored in *pMaxIndex, in the range 0 <=
**                           index < n, if pMaxIndex is not NULL.
** ===================================================================
*/

#define AFR1_afr16Min(pX,n,pMinIndex) afr16Min(pX,n,pMinIndex)
Frac16 afr16Min(Frac16 *pX,UInt16 n,UInt16 *pMinIndex);
/*
** ===================================================================
**     Method      :  AFR1_afr16Min (component DSP_Func_AFR)
**
**     Description :
**         The function searches the input array for the minimum
**         fractional value. This method cannot be disabled if Use
**         Assembler Files property is enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pX              - Pointer to the input array of fractional
**                           data values.
**         n               - The length of the array.
**       * pMinIndex       - A pointer to a variable in
**                           which to store the index of the minimum
**                           value of the input array; may be NULL.
**     Returns     :
**         ---             - The function returns the value of the
**                           minimum array element as the return value
**                           of the function. In addition, the array
**                           index of the minimum array element may be
**                           stored in *pMinIndex, in the range 0 <=
**                           index < n, if pMinIndex is not NULL.
** ===================================================================
*/

#define AFR1_afr16Msu_r(pW,pX,pY,pZ,n) afr16Msu_r(pW,pX,pY,pZ,n)
void afr16Msu_r(Frac16 *pW,Frac16 *pX,Frac16 *pY,Frac16 *pZ,UInt16 n);
/*
** ===================================================================
**     Method      :  AFR1_afr16Msu_r (component DSP_Func_AFR)
**
**     Description :
**         The function multiplies the corresponding elements of each X
**         and Y input array and subtracts the result from the
**         corresponding element of the W input array; i.e., pZ[i] =
**         pW[i] - (pX[i] * pY[i]), 0 <= i < n. This method cannot be
**         disabled if Use Assembler Files property is enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pW              - Pointer to the input array of fractional
**                           data values against which (pX[i] * pY[i])
**                           will be subtracted.
**       * pX              - Pointer to the input array of fractional
**                           data values to be multiplied.
**       * pY              - Pointer to the input array of fractional
**                           data values to be multiplied.
**       * pZ              - Pointer to the output array.
**         n               - The length of all input and output arrays.
**     Returns     : Nothing
** ===================================================================
*/

#define AFR1_afr16Mult(pX,pY,pZ,n) afr16Mult(pX,pY,pZ,n)
void afr16Mult(Frac16 *pX,Frac16 *pY,Frac16 *pZ,UInt16 n);
/*
** ===================================================================
**     Method      :  AFR1_afr16Mult (component DSP_Func_AFR)
**
**     Description :
**         The function multiplies the corresponding elements of each
**         input array; i.e., pZ[i] = pX[i] * pY[i], 0 <= i < n. The
**         mult_r function differs from mult in that mult_r rounds the
**         result, but mult truncates the result. This method cannot be
**         disabled if Use Assembler Files property is enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pX              - Pointer to the first input array.
**       * pY              - Pointer to the second input array.
**       * pZ              - Pointer to the output array.
**         n               - The length of all input and output arrays.
**     Returns     : Nothing
** ===================================================================
*/

#define AFR1_afr16Mult_r(pX,pY,pZ,n) afr16Mult_r(pX,pY,pZ,n)
void afr16Mult_r(Frac16 *pX,Frac16 *pY,Frac16 *pZ,UInt16 n);
/*
** ===================================================================
**     Method      :  AFR1_afr16Mult_r (component DSP_Func_AFR)
**
**     Description :
**         The function multiplies the corresponding elements of each
**         input array; i.e., pZ[i] = pX[i] * pY[i], 0 <= i < n. The
**         mult_r function differs from mult in that mult_r rounds the
**         result, but mult truncates the result. This method cannot be
**         disabled if Use Assembler Files property is enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pX              - Pointer to the first input array.
**       * pY              - Pointer to the second input array.
**       * pZ              - Pointer to the output array.
**         n               - The length of all input and output arrays.
**     Returns     : Nothing
** ===================================================================
*/

#define AFR1_afr16Negate(pX,pZ,n) afr16Negate(pX,pZ,n)
void afr16Negate(Frac16 *pX,Frac16 *pZ,UInt16 n);
/*
** ===================================================================
**     Method      :  AFR1_afr16Negate (component DSP_Func_AFR)
**
**     Description :
**         The function negates each fractional element of the input
**         array pointed to by pX; i.e., pZ[i] = - pX[i], 0 <= i < n.
**         This method cannot be disabled if Use Assembler Files
**         property is enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pX              - Pointer to an input array of fractional data
**                           values.
**       * pZ              - Pointer to an output array of fractional
**                           data values.
**         n               - The length of the input and output arrays.
**     Returns     : Nothing
** ===================================================================
*/

#define AFR1_afr16Rand(pZ,n) afr16Rand(pZ,n)
void afr16Rand(Frac16 *pZ,UInt16 n);
/*
** ===================================================================
**     Method      :  AFR1_afr16Rand (component DSP_Func_AFR)
**
**     Description :
**         The function calculates n random 16-bit fractional numbers
**         and stores them in the output array pointed to by pZ; i.e.,
**         pZ[i] = rand(), 0 <= i < n. This method cannot be disabled
**         if Use Assembler Files property is enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pZ              - Pointer to an output array of fractional
**                           data values.
**         n               - The length of the output array.
**     Returns     : Nothing
** ===================================================================
*/

#define AFR1_afr16Sqrt(pX,pZ,n) afr16Sqrt(pX,pZ,n)
void afr16Sqrt(Frac16 *pX,Frac16 *pZ,UInt16 n);
/*
** ===================================================================
**     Method      :  AFR1_afr16Sqrt (component DSP_Func_AFR)
**
**     Description :
**         The function calculates the square root of each fractional
**         element of the input array pointed to by pX; i.e., pZ[i] =
**         sqrt(pX[i]), 0 <= i < n. This method cannot be disabled if
**         Use Assembler Files property is enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pX              - Pointer to an input array of fractional data
**                           values.
**       * pZ              - Pointer to an output array of fractional
**                           data values.
**         n               - The length of the input and output arrays.
**     Returns     : Nothing
** ===================================================================
*/

#define AFR1_afr16Sub(pX,pY,pZ,n) afr16Sub(pX,pY,pZ,n)
void afr16Sub(Frac16 *pX,Frac16 *pY,Frac16 *pZ,UInt16 n);
/*
** ===================================================================
**     Method      :  AFR1_afr16Sub (component DSP_Func_AFR)
**
**     Description :
**         The function subtracts the corresponding elements of the pY
**         input array from the pX input array; i.e., pZ[i] = pX[i] -
**         pY[i], 0 <= i < n. This method cannot be disabled if Use
**         Assembler Files property is enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pX              - Pointer to the first input array of
**                           fractional data values.
**       * pY              - Pointer to the second input array of
**                           fractional data values.
**       * pZ              - Pointer to the output array of fractional
**                           results.
**         n               - The length of all input and output arrays.
**     Returns     : Nothing
** ===================================================================
*/

#define AFR1_afr32Abs(pX,pZ,n) afr32Abs(pX,pZ,n)
void afr32Abs(Frac32 *pX,Frac32 *pZ,UInt16 n);
/*
** ===================================================================
**     Method      :  AFR1_afr32Abs (component DSP_Func_AFR)
**
**     Description :
**         The function calculates the absolute value of each
**         fractional element of the input array pointed to by pX; i.e.,
**         pZ[i] = pX[i], 0 <= i < n. This method cannot be disabled if
**         Use Assembler Files property is enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pX              - Pointer to an input array of fractional data
**                           values.
**       * pZ              - Pointer to an output array of fractional
**                           data values.
**         n               - The length of the input and output arrays.
**     Returns     : Nothing
** ===================================================================
*/

#define AFR1_afr32Add(pX,pY,pZ,n) afr32Add(pX,pY,pZ,n)
void afr32Add(Frac32 *pX,Frac32 *pY,Frac32 *pZ,UInt16 n);
/*
** ===================================================================
**     Method      :  AFR1_afr32Add (component DSP_Func_AFR)
**
**     Description :
**         The function totals the corresponding elements of each input
**         array; i.e., pZ[i] = pX[i] + pY[i], 0 <= i < n. This method
**         cannot be disabled if Use Assembler Files property is
**         enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pX              - Pointer to the first input array of
**                           fractional data values.
**       * pY              - Pointer to the second input array of
**                           fractional data values..
**       * pZ              - Pointer to the output array of fractional
**                           results.
**         n               - The length of all input and output arrays.
**     Returns     : Nothing
** ===================================================================
*/

#define AFR1_afr32Div(pX,pY,pZ,n) afr32Div(pX,pY,pZ,n)
void afr32Div(Frac32 *pX,Frac16 *pY,Frac16 *pZ,UInt16 n);
/*
** ===================================================================
**     Method      :  AFR1_afr32Div (component DSP_Func_AFR)
**
**     Description :
**         The function divides the corresponding elements of each
**         input array; i.e., pZ[i] = pX[i] / pY[i], 0 <= i < n. In
**         this equation, pX[i] and pY[i] must be positive, and pY[i]
**         must be greater than or equal to pX[i]. This method cannot
**         be disabled if Use Assembler Files property is enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pX              - Pointer to the input array of dividends.
**       * pY              - Pointer to the input array of divisors.
**       * pZ              - Pointer to the output array of quotients.
**         n               - The length of all input and output arrays.
**     Returns     : Nothing
** ===================================================================
*/

#define AFR1_afr32Equal(pX,pY,n) afr32Equal(pX,pY,n)
bool afr32Equal(Frac32 *pX,Frac32 *pY,UInt16 n);
/*
** ===================================================================
**     Method      :  AFR1_afr32Equal (component DSP_Func_AFR)
**
**     Description :
**         The function compares the corresponding elements of each
**         fractional array for equality, i.e., pX[i] == pY[i], 0 <= i
**         < n. This method cannot be disabled if Use Assembler Files
**         property is enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pX              - Pointer to an input array of fractional data
**                           values.
**       * pY              - Pointer to an input array of fractional data
**                           values.
**         n               - The length of both input arrays.
**     Returns     :
**         ---             - The function returns true if all
**                           corresponding elements of the two input
**                           arrays are equal. If any element of the two
**                           input arrays is not equal, equal returns
**                           false.
** ===================================================================
*/

#define AFR1_afr32Mac(pW,pX,pY,pZ,n) afr32Mac(pW,pX,pY,pZ,n)
void afr32Mac(Frac32 *pW,Frac16 *pX,Frac16 *pY,Frac32 *pZ,UInt16 n);
/*
** ===================================================================
**     Method      :  AFR1_afr32Mac (component DSP_Func_AFR)
**
**     Description :
**         The function multiplies the corresponding elements of each X
**         and Y input array and adds the result to the corresponding
**         element of the W input array; i.e., pZ[i] = (pX[i] * pY[i])
**         + pW[i], 0 <= i < n. This method cannot be disabled if Use
**         Assembler Files property is enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pW              - Pointer to the input array of fractional
**                           data values to be added.
**       * pX              - Pointer to the input array of fractional
**                           data values to be multiplied.
**       * pY              - Pointer to the input array of fractional
**                           data values to be multiplied.
**       * pZ              - Pointer to the output array.
**         n               - The length of all input and output arrays.
**     Returns     : Nothing
** ===================================================================
*/

#define AFR1_afr32Mac_r(pW,pX,pY,pZ,n) afr32Mac_r(pW,pX,pY,pZ,n)
void afr32Mac_r(Frac32 *pW,Frac16 *pX,Frac16 *pY,Frac16 *pZ,UInt16 n);
/*
** ===================================================================
**     Method      :  AFR1_afr32Mac_r (component DSP_Func_AFR)
**
**     Description :
**         The function multiplies the corresponding elements of each X
**         and Y input array and adds the result to the corresponding
**         element of the W input array; i.e., pZ[i] = (pX[i] * pY[i])
**         + pW[i], 0 <= i < n. This method cannot be disabled if Use
**         Assembler Files property is enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pW              - Pointer to the input array of fractional
**                           data values to be added.
**       * pX              - Pointer to the input array of fractional
**                           data values to be multiplied.
**       * pY              - Pointer to the input array of fractional
**                           data values to be multiplied.
**       * pZ              - Pointer to the output array.
**         n               - The length of all input and output arrays.
**     Returns     : Nothing
** ===================================================================
*/

#define AFR1_afr32Max(pX,n,pMaxIndex) afr32Max(pX,n,pMaxIndex)
Frac32 afr32Max(Frac32 *pX,UInt16 n,UInt16 *pMaxIndex);
/*
** ===================================================================
**     Method      :  AFR1_afr32Max (component DSP_Func_AFR)
**
**     Description :
**         The function searches the input array for the maximum
**         fractional value. This method cannot be disabled if Use
**         Assembler Files property is enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pX              - Pointer to the input array of fractional
**                           data values.
**         n               - The length of the array.
**       * pMaxIndex       - A pointer to a variable in
**                           which to store the index of the maximum
**                           value of the input array; may be NULL.
**     Returns     :
**         ---             - The function returns the value of the
**                           maximum array element as the return value
**                           of the function. In addition, the array
**                           index of the maximum array element may be
**                           stored in *pMaxIndex, in the range 0 <=
**                           index < n, if pMaxIndex is not NULL.
** ===================================================================
*/

#define AFR1_afr32Min(pX,n,pMinIndex) afr32Min(pX,n,pMinIndex)
Frac32 afr32Min(Frac32 *pX,UInt16 n,UInt16 *pMinIndex);
/*
** ===================================================================
**     Method      :  AFR1_afr32Min (component DSP_Func_AFR)
**
**     Description :
**         The function searches the input array for the minimum
**         fractional value. This method cannot be disabled if Use
**         Assembler Files property is enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pX              - Pointer to the input array of fractional
**                           data values.
**         n               - The length of the array.
**       * pMinIndex       - A pointer to a variable in
**                           which to store the index of the minimum
**                           value of the input array; may be NULL.
**     Returns     :
**         ---             - The function returns the value of the
**                           minimum array element as the return value
**                           of the function. In addition, the array
**                           index of the minimum array element may be
**                           stored in *pMinIndex, in the range 0 <=
**                           index < n, if pMinIndex is not NULL.
** ===================================================================
*/

#define AFR1_afr32Msu(pW,pX,pY,pZ,n) afr32Msu(pW,pX,pY,pZ,n)
void afr32Msu(Frac32 *pW,Frac16 *pX,Frac16 *pY,Frac32 *pZ,UInt16 n);
/*
** ===================================================================
**     Method      :  AFR1_afr32Msu (component DSP_Func_AFR)
**
**     Description :
**         The function multiplies the corresponding elements of each X
**         and Y input array and subtracts the result from the
**         corresponding element of the W input array; i.e., pZ[i] =
**         pW[i] - (pX[i] * pY[i]), 0 <= i < n. This method cannot be
**         disabled if Use Assembler Files property is enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pW              - Pointer to the input array of fractional
**                           data values against which (pX[i] * pY[i])
**                           will be subtracted.
**       * pX              - Pointer to the input array of fractional
**                           data values to be multiplied.
**       * pY              - Pointer to the input array of fractional
**                           data values to be multiplied.
**       * pZ              - Pointer to the output array.
**         n               - The length of all input and output arrays.
**     Returns     : Nothing
** ===================================================================
*/

#define AFR1_afr32Msu_r(pW,pX,pY,pZ,n) afr32Msu_r(pW,pX,pY,pZ,n)
void afr32Msu_r(Frac32 *pW,Frac16 *pX,Frac16 *pY,Frac16 *pZ,UInt16 n);
/*
** ===================================================================
**     Method      :  AFR1_afr32Msu_r (component DSP_Func_AFR)
**
**     Description :
**         The function multiplies the corresponding elements of each X
**         and Y input array and subtracts the result from the
**         corresponding element of the W input array; i.e., pZ[i] =
**         pW[i] - (pX[i] * pY[i]), 0 <= i < n. This method cannot be
**         disabled if Use Assembler Files property is enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pW              - Pointer to the input array of fractional
**                           data values against which (pX[i] * pY[i])
**                           will be subtracted.
**       * pX              - Pointer to the input array of fractional
**                           data values to be multiplied.
**       * pY              - Pointer to the input array of fractional
**                           data values to be multiplied.
**       * pZ              - Pointer to the output array.
**         n               - The length of all input and output arrays.
**     Returns     : Nothing
** ===================================================================
*/

#define AFR1_afr32Mult(pX,pY,pZ,n) afr32Mult(pX,pY,pZ,n)
void afr32Mult(Frac16 *pX,Frac16 *pY,Frac32 *pZ,UInt16 n);
/*
** ===================================================================
**     Method      :  AFR1_afr32Mult (component DSP_Func_AFR)
**
**     Description :
**         The function multiplies the corresponding elements of each
**         input array; i.e., pZ[i] = pX[i] * pY[i], 0 <= i < n. The
**         mult_r function differs from mult in that mult_r rounds the
**         result, but mult truncates the result. This method cannot be
**         disabled if Use Assembler Files property is enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pX              - Pointer to the first input array.
**       * pY              - Pointer to the second input array.
**       * pZ              - Pointer to the output array.
**         n               - The length of all input and output arrays.
**     Returns     : Nothing
** ===================================================================
*/

#define AFR1_afr32Mult_ls(pX,pY,pZ,n) afr32Mult_ls(pX,pY,pZ,n)
void afr32Mult_ls(Frac32 *pX,Frac16 *pY,Frac32 *pZ,UInt16 n);
/*
** ===================================================================
**     Method      :  AFR1_afr32Mult_ls (component DSP_Func_AFR)
**
**     Description :
**         The function multiplies the corresponding elements of each
**         input array; i.e., pZ[i] = pX[i] * pY[i], 0 <= i < n. The
**         mult_r function differs from mult in that mult_r rounds the
**         result, but mult truncates the result. This method cannot be
**         disabled if Use Assembler Files property is enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pX              - Pointer to the first input array.
**       * pY              - Pointer to the second input array.
**       * pZ              - Pointer to the output array.
**         n               - The length of all input and output arrays.
**     Returns     : Nothing
** ===================================================================
*/

#define AFR1_afr32Negate(pX,pZ,n) afr32Negate(pX,pZ,n)
void afr32Negate(Frac32 *pX,Frac32 *pZ,UInt16 n);
/*
** ===================================================================
**     Method      :  AFR1_afr32Negate (component DSP_Func_AFR)
**
**     Description :
**         The function negates each fractional element of the input
**         array pointed to by pX; i.e., pZ[i] = - pX[i], 0 <= i < n.
**         This method cannot be disabled if Use Assembler Files
**         property is enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pX              - Pointer to an input array of fractional data
**                           values.
**       * pZ              - Pointer to an output array of fractional
**                           data values.
**         n               - The length of the input and output arrays.
**                           The length of the input and output arrays.
**     Returns     : Nothing
** ===================================================================
*/

#define AFR1_afr32Round(pX,pZ,n) afr32Round(pX,pZ,n)
void afr32Round(Frac32 *pX,Frac16 *pZ,UInt16 n);
/*
** ===================================================================
**     Method      :  AFR1_afr32Round (component DSP_Func_AFR)
**
**     Description :
**         The function converts each 32-bit fractional element of the
**         input array pointed to by pX into a 16-bit fractional value,
**         rounding the least significant bit; i.e., pZ[i] = round(pX[i]
**         ), 0 <= i < n. This method cannot be disabled if Use
**         Assembler Files property is enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pX              - Pointer to an input array of fractional data
**                           values.
**       * pZ              - Pointer to an output array of fractional
**                           data values.
**         n               - The length of the input and output arrays.
**     Returns     : Nothing
** ===================================================================
*/

#define AFR1_afr32Sqrt(pX,pZ,n) afr32Sqrt(pX,pZ,n)
void afr32Sqrt(Frac32 *pX,Frac16 *pZ,UInt16 n);
/*
** ===================================================================
**     Method      :  AFR1_afr32Sqrt (component DSP_Func_AFR)
**
**     Description :
**         The function calculates the square root of each fractional
**         element of the input array pointed to by pX; i.e., pZ[i] =
**         sqrt(pX[i]), 0 <= i < n. This method cannot be disabled if
**         Use Assembler Files property is enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pX              - Pointer to an input array of fractional data
**                           values.
**       * pZ              - Pointer to an output array of fractional
**                           data values.
**         n               - The length of the input and output arrays.
**     Returns     : Nothing
** ===================================================================
*/

#define AFR1_afr32Sub(pX,pY,pZ,n) afr32Sub(pX,pY,pZ,n)
void afr32Sub(Frac32 *pX,Frac32 *pY,Frac32 *pZ,UInt16 n);
/*
** ===================================================================
**     Method      :  AFR1_afr32Sub (component DSP_Func_AFR)
**
**     Description :
**         The function subtracts the corresponding elements of the pY
**         input array from the pX input array; i.e., pZ[i] = pX[i] -
**         pY[i], 0 <= i < n. This method cannot be disabled if Use
**         Assembler Files property is enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pX              - Pointer to the first input array of
**                           fractional data values.
**       * pY              - Pointer to the second input array of
**                           fractional data values.
**       * pZ              - Pointer to the output array of fractional
**                           results.
**         n               - The length of all input and output arrays.
**     Returns     : Nothing
** ===================================================================
*/

/* END AFR1. */

#endif /* ifndef __AFR1 */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.00 [04.35]
**     for the Freescale 56800 series of microcontrollers.
**
** ###################################################################
*/
