/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**
**     Copyright : 1997 - 2009 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/
/* File: memTarget.c */

#include "port.h"
#include "mem.h"
#include "arch.h"
#include "assert.h"
#include <string.h>
#include <stdio.h>


/*******************************************************
* specific memory Package for 56F8367
*******************************************************/

/*****************************************************************************
*
* Module:
*    memIsIM()
*
* Description:
*    This function determines if the pointer to memory passed in is
*    in internal memory of the 56F8367.
*
* Returns:
*    true  - if memory is in internal memory
*    false - if memory is not in internal memory
*
* Global Data:
*    None
*
* Arguments:
*    memblock - void * pointer to a memory location
*
* Range Issues:
*
* Special Issues:
*
*******************************************************************************/
bool    memIsIM     (void * memblock)
{
 return ((UInt32)memblock < (UInt32)0x8000);
}


/*****************************************************************************
*
* Module:
*    memIsEM()
*
* Description:
*    This function determines if the pointer to memory passed in is
*    in external memory of the 56F8367.
*
* Returns:
*    true  - if memory is in external memory
*    false - if memory is not in external memory
*
* Global Data:
*    None
*
* Arguments:
*    memblock - void * pointer to a memory location
*
* Range Issues:
*
* Special Issues:
*
*******************************************************************************/
bool    memIsEM     (void * memblock)
{
return ((UInt32)memblock >= (UInt32)0x8000);
}
