/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : TFR1.H
**     Project   : TP1
**     Processor : 56F8367
**     Component : DSP_Func_TFR
**     Version   : Component 01.036, Driver 01.10, CPU db: 2.87.058
**     Compiler  : Metrowerks DSP C Compiler
**     Date/Time : 27/04/2015, 20:32
**     Abstract  :
**          This bean implements trigonometric functions, such as sine and cosine,
**          for fractional types as library routines. The function library provides
**          such trigonometric functions for both 16-bit (short) fractional types.
**          For portability, we have defined a short 16-bit fractional type as Frac16.
**     Settings  :
**          Bean Name                      : TFR1
**          Use Assembler Files            : yes
**          Memory Management Library      : MEM1
**          Basic Fractional Math Library  : MFR1
**     Contents  :
**         tfr16SinPIx                   - Frac16 TFR1_tfr16SinPIx(Frac16 x);
**         tfr16SinPIxLUT                - Frac16 TFR1_tfr16SinPIxLUT(tfr16_tSinPIxLUT *pSWG, Frac16 PhasePIx);
**         tfr16CosPIx                   - Frac16 TFR1_tfr16CosPIx(Frac16 x);
**         tfr16SinPIxLUTCreate          - tfr16_tSinPIxLUT * TFR1_tfr16SinPIxLUTCreate(Frac16 *pSineTable, UInt16...
**         tfr16SinPIxLUTDestroy         - void TFR1_tfr16SinPIxLUTDestroy(tfr16_tSinPIxLUT *pSWG);
**         tfr16SinPIxLUTInit            - void TFR1_tfr16SinPIxLUTInit(tfr16_tSinPIxLUT *pSWG, Frac16 *pSineTable,...
**         tfr16CosPIxLUT                - Frac16 TFR1_tfr16CosPIxLUT(tfr16_tCosPIxLUT *pSWG, Frac16 PhasePIx);
**         tfr16CosPIxLUTCreate          - tfr16_tCosPIxLUT * TFR1_tfr16CosPIxLUTCreate(Frac16 *pSineTable, UInt16...
**         tfr16CosPIxLUTDestroy         - void TFR1_tfr16CosPIxLUTDestroy(tfr16_tCosPIxLUT *pSWG);
**         tfr16CosPIxLUTInit            - void TFR1_tfr16CosPIxLUTInit(tfr16_tCosPIxLUT *pSWG, Frac16 *pSineTable,...
**         tfr16AsinOverPI               - Frac16 TFR1_tfr16AsinOverPI(Frac16 x);
**         tfr16AcosOverPI               - Frac16 TFR1_tfr16AcosOverPI(Frac16 x);
**         tfr16AtanOverPI               - Frac16 TFR1_tfr16AtanOverPI(Frac16 x);
**         tfr16Atan2OverPI              - Frac16 TFR1_tfr16Atan2OverPI(Frac16 y, Frac16 x);
**         tfr16SineWaveGenIDTL          - void TFR1_tfr16SineWaveGenIDTL(tfr16_tSineWaveGenIDTL *pSWG, Frac16 *pValues,...
**         tfr16SineWaveGenIDTLDestroy   - void TFR1_tfr16SineWaveGenIDTLDestroy(tfr16_tSineWaveGenIDTL *pSWG);
**         tfr16SineWaveGenRDTL          - void TFR1_tfr16SineWaveGenRDTL(tfr16_tSineWaveGenRDTL *pSWG, Frac16 *pValues,...
**         tfr16SineWaveGenRDTLDestroy   - void TFR1_tfr16SineWaveGenRDTLDestroy(tfr16_tSineWaveGenRDTL *pSWG);
**         tfr16SineWaveGenRDITL         - void TFR1_tfr16SineWaveGenRDITL(tfr16_tSineWaveGenRDITL *pSWG, Frac16...
**         tfr16SineWaveGenRDITLDestroy  - void TFR1_tfr16SineWaveGenRDITLDestroy(tfr16_tSineWaveGenRDITL *pSWG);
**         tfr16SineWaveGenRDITLQ        - void TFR1_tfr16SineWaveGenRDITLQ(tfr16_tSineWaveGenRDITLQ *pSWG, Frac16...
**         tfr16SineWaveGenRDITLQDestroy - void TFR1_tfr16SineWaveGenRDITLQDestroy(tfr16_tSineWaveGenRDITLQ *pSWG);
**         tfr16SineWaveGenPAM           - void TFR1_tfr16SineWaveGenPAM(tfr16_tSineWaveGenPAM *pSWG, Frac16 *pValues,...
**         tfr16SineWaveGenPAMDestroy    - void TFR1_tfr16SineWaveGenPAMDestroy(tfr16_tSineWaveGenPAM *pSWG);
**         tfr16SineWaveGenDOM           - void TFR1_tfr16SineWaveGenDOM(tfr16_tSineWaveGenDOM *pSWG, Frac16 *pValues,...
**         tfr16SineWaveGenDOMDestroy    - void TFR1_tfr16SineWaveGenDOMDestroy(tfr16_tSineWaveGenDOM *pSWG);
**         tfr16SineWaveGenIDTLCreate    - tfr16_tSineWaveGenIDTL* TFR1_tfr16SineWaveGenIDTLCreate(Frac16 *pSineTable,...
**         tfr16SineWaveGenIDTLInit      - void TFR1_tfr16SineWaveGenIDTLInit(tfr16_tSineWaveGenIDTL *pSWG, Frac16...
**         tfr16SineWaveGenRDTLCreate    - tfr16_tSineWaveGenRDTL * TFR1_tfr16SineWaveGenRDTLCreate(Frac16 *pSineTable,...
**         tfr16SineWaveGenRDTLInit      - void TFR1_tfr16SineWaveGenRDTLInit(tfr16_tSineWaveGenRDTL *pSWG, Frac16...
**         tfr16SineWaveGenRDITLCreate   - tfr16_tSineWaveGenRDITL * TFR1_tfr16SineWaveGenRDITLCreate(Frac16...
**         tfr16SineWaveGenRDITLInit     - void TFR1_tfr16SineWaveGenRDITLInit(tfr16_tSineWaveGenRDITL *pSWG, Frac16...
**         tfr16SineWaveGenRDITLQCreate  - tfr16_tSineWaveGenRDITLQ * TFR1_tfr16SineWaveGenRDITLQCreate(Frac16...
**         tfr16SineWaveGenRDITLQInit    - void TFR1_tfr16SineWaveGenRDITLQInit(tfr16_tSineWaveGenRDITLQ *pSWG, Frac16...
**         tfr16SineWaveGenPAMCreate     - tfr16_tSineWaveGenPAM * TFR1_tfr16SineWaveGenPAMCreate(Int16 SineFreq, Int16...
**         tfr16SineWaveGenPAMInit       - void TFR1_tfr16SineWaveGenPAMInit(tfr16_tSineWaveGenPAM *pSWG, Int16...
**         tfr16SineWaveGenDOMCreate     - tfr16_tSineWaveGenDOM * TFR1_tfr16SineWaveGenDOMCreate(Int16 SineFreq, Int16...
**         tfr16SineWaveGenDOMInit       - void TFR1_tfr16SineWaveGenDOMInit(tfr16_tSineWaveGenDOM *pSWG, Int16...
**         tfr16WaveGenRDITLQ            - Frac16 TFR1_tfr16WaveGenRDITLQ(tfr16_tWaveGenRDITLQ *pSWG, Frac16...
**         tfr16WaveGenRDITLQCreate      - tfr16_tWaveGenRDITLQ * TFR1_tfr16WaveGenRDITLQCreate(Frac16 *pSineTable,...
**         tfr16WaveGenRDITLQDestroy     - void TFR1_tfr16WaveGenRDITLQDestroy(tfr16_tWaveGenRDITLQ *pSWG);
**         tfr16WaveGenRDITLQInit        - void TFR1_tfr16WaveGenRDITLQInit(tfr16_tWaveGenRDITLQ *pSWG, Frac16...
**
**     (c) Freescale Semiconductor
**     2004 All Rights Reserved
**
**     Copyright : 1997 - 2009 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef __TFR1
#define __TFR1

/* MODULE TFR1. */

/*Include shared modules, which are used for whole project*/
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited beans */
#include "MFR1.h"
#include "MEM1.h"
#include "port.h"
#include "dspfunc.h"
#include "tfr16.h"

#include "Cpu.h"




#define TFR1_tfr16SinPIx(x) tfr16SinPIx(x)
Frac16 tfr16SinPIx(Frac16 x);
/*
** ===================================================================
**     Method      :  TFR1_tfr16SinPIx (component DSP_Func_TFR)
**
**     Description :
**         The function calculates sine (pi * x).
**     Parameters  :
**         NAME            - DESCRIPTION
**         x               - The input data value.
**     Returns     :
**         ---             - The function returns result of the sine
**                           (pi * x) calculation.
** ===================================================================
*/

#define TFR1_tfr16CosPIx(x) tfr16CosPIx(x)
Frac16 tfr16CosPIx(Frac16 x);
/*
** ===================================================================
**     Method      :  TFR1_tfr16CosPIx (component DSP_Func_TFR)
**
**     Description :
**         The function calculates cosine (pi * x).
**     Parameters  :
**         NAME            - DESCRIPTION
**         x               - The input data value.
**     Returns     :
**         ---             - The function returns result of the
**                           cosine (pi * x) calculation.
** ===================================================================
*/

#define TFR1_tfr16SinPIxLUT(pSWG, PhasePIx) tfr16SinPIxLUT(pSWG, PhasePIx)
/*
** ===================================================================
**     Method      :  TFR1_tfr16SinPIxLUT (component DSP_Func_TFR)
**
**     Description :
**         The function generates one sine value and returns it.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pSWG            - Pointer to tfr16_tSinPIxLUT type
**                           defined in tfr16.h header file. It
**                           points to private data for the SinPIxLUT
**                           function.
**         PhasePIx        - The phase, -pi to pi, from
**                           which the sine value is calculated.
**     Returns     :
**         ---             - The function returns one sine value.
** ===================================================================
*/

#define TFR1_tfr16SinPIxLUTCreate(pSineTable, SineTableLength) tfr16SinPIxLUTCreate(pSineTable, SineTableLength)
/*
** ===================================================================
**     Method      :  TFR1_tfr16SinPIxLUTCreate (component DSP_Func_TFR)
**
**     Description :
**         The function allocates the structure of type
**         tfr16_tSinPIxLUT. This method is enabled only if Memory
**         management property is enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pSineTable      - Pointer to a sine look-up
**                           table which is allocated and filled by the
**                           application.
**         SineTableLength - The length of the
**                           sine look-up table.
**     Returns     :
**         ---             - The function returns a pointer to the
**                           tfr16_tSinPIxLUT structure which is used by
**                           all other tfr16SinPIxLUT functions.
** ===================================================================
*/

#define TFR1_tfr16SinPIxLUTDestroy(pSWG) tfr16SinPIxLUTDestroy(pSWG)
/*
** ===================================================================
**     Method      :  TFR1_tfr16SinPIxLUTDestroy (component DSP_Func_TFR)
**
**     Description :
**         The function frees the tfr16_tSinPIxLUT data structures(s)
**         previously allocated by tfr16SinPIxLUTCreate. This method is
**         enabled only if Memory management property is enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pSWG            - Pointer to tfr16_tSinPIxLUT type defined
**                           in tfr16.h header file. It points to
**                           private data for the SinPIxLUT function.
**     Returns     : Nothing
** ===================================================================
*/

#define TFR1_tfr16SinPIxLUTInit(pSWG, pSineTable, SineTableLength) tfr16SinPIxLUTInit(pSWG, pSineTable, SineTableLength)
/*
** ===================================================================
**     Method      :  TFR1_tfr16SinPIxLUTInit (component DSP_Func_TFR)
**
**     Description :
**         The function initializes the tfr16_tSinPIxLUT data
**         structure used by all tfr16SinPIxLUT functions. The
**         tfr16_tSinPIxLUT data structure pointed to by pSWG must
**         have been allocated prior to calling tfr16SinPIxLUTInit.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pSWG            - Pointer to tfr16_tSinPIxLUT type
**                           defined in tfr16.h header file. It
**                           points to private data for the SinPIxLUT
**                           function.
**       * pSineTable      - Pointer to a sine look-up
**                           table which is allocated and filled by
**                           the application.
**         SineTableLength - The length of
**                           the sine look-up table.
**     Returns     : Nothing
** ===================================================================
*/

#define TFR1_tfr16CosPIxLUT(pSWG, PhasePIx) tfr16CosPIxLUT(pSWG, PhasePIx)
/*
** ===================================================================
**     Method      :  TFR1_tfr16CosPIxLUT (component DSP_Func_TFR)
**
**     Description :
**         The function generates one cosine value and returns it.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pSWG            - Pointer to tfr16_tCosPIxLUT type
**                           defined in tfr16.h header file. It
**                           points to private data for the CosPIxLUT
**                           function.
**         PhasePIx        - The phase, -pi to pi, from
**                           which the cosine value is calculated.
**     Returns     :
**         ---             - The function returns one cosine value.
** ===================================================================
*/

#define TFR1_tfr16CosPIxLUTCreate(pSineTable, SineTableLength) tfr16CosPIxLUTCreate(pSineTable, SineTableLength)
/*
** ===================================================================
**     Method      :  TFR1_tfr16CosPIxLUTCreate (component DSP_Func_TFR)
**
**     Description :
**         The function allocates the structure of type
**         tfr16_tCosPIxLUT. This method is enabled only if Memory
**         management property is enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pSineTable      - Pointer to a sine look-up
**                           table which is allocated and filled by the
**                           application.
**         SineTableLength - The length of the
**                           sine look-up table.
**     Returns     :
**         ---             - The function returns a pointer to the
**                           tfr16_tCosPIxLUT structure, which is used
**                           by all other tfr16CosPIxLUT functions.
** ===================================================================
*/

#define TFR1_tfr16CosPIxLUTDestroy(pSWG) tfr16CosPIxLUTDestroy(pSWG)
/*
** ===================================================================
**     Method      :  TFR1_tfr16CosPIxLUTDestroy (component DSP_Func_TFR)
**
**     Description :
**         The function frees the tfr16_tCosPIxLUT data structures(s)
**         previously allocated by tfr16CosPIxLUTCreate. This method is
**         enabled only if Memory management property is enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pSWG            - Pointer to tfr16_tCosPIxLUT type defined
**                           in tfr16.h header file. It points to
**                           private data for the CosPIxLUT function.
**     Returns     : Nothing
** ===================================================================
*/

#define TFR1_tfr16CosPIxLUTInit(pSWG, pSineTable, SineTableLength) tfr16CosPIxLUTInit(pSWG, pSineTable, SineTableLength)
/*
** ===================================================================
**     Method      :  TFR1_tfr16CosPIxLUTInit (component DSP_Func_TFR)
**
**     Description :
**         The function initializes the tfr16_tCosPIxLUT data
**         structure used by all tfr16CosPIxLUT functions. The
**         tfr16_tCosPIxLUT data structure pointed to by pSWG must
**         have been allocated prior to calling tfr16CosPIxLUTInit.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pSWG            - Pointer to tfr16_tCosPIxLUT type
**                           defined in tfr16.h header file. It
**                           points to private data for the CosPIxLUT
**                           function.
**       * pSineTable      - Pointer to a sine look-up
**                           table which is allocated and filled by
**                           the application.
**         SineTableLength - Pointer to a
**                           sine look-up table which is allocated
**                           and filled by the application.
**     Returns     : Nothing
** ===================================================================
*/

#define TFR1_tfr16AsinOverPI(x) tfr16AsinOverPI(x)
/*
** ===================================================================
**     Method      :  TFR1_tfr16AsinOverPI (component DSP_Func_TFR)
**
**     Description :
**         The function calculates the Arcsin function of the
**         fractional input value x, and divides that result by pi;
**         i.e., (Arcsin x) / pi.
**     Parameters  :
**         NAME            - DESCRIPTION
**         x               - The input data value.
**     Returns     :
**         ---             - The function returns result of the
**                           (Arcsin x) / pi calculation. This result
**                           represents the angle in radians whose
**                           sine is x, divided by pi.
** ===================================================================
*/

#define TFR1_tfr16AcosOverPI(x) tfr16AcosOverPI(x)
/*
** ===================================================================
**     Method      :  TFR1_tfr16AcosOverPI (component DSP_Func_TFR)
**
**     Description :
**         The function calculates the Arccos function of the
**         fractional input value x, and divides that result by pi;
**         i.e., (Arccos x) / pi.
**     Parameters  :
**         NAME            - DESCRIPTION
**         x               - The input data value.
**     Returns     :
**         ---             - The function returns result of the
**                           (Arccos x) / pi calculation. This result
**                           represents the angle in radians whose
**                           cosine is x, divided by pi.
** ===================================================================
*/

#define TFR1_tfr16AtanOverPI(x) tfr16AtanOverPI(x)
/*
** ===================================================================
**     Method      :  TFR1_tfr16AtanOverPI (component DSP_Func_TFR)
**
**     Description :
**         The function calculates the Arctan function of the
**         fractional input value x, and divides that result by pi;
**         i.e., (Arctan x) / pi.
**     Parameters  :
**         NAME            - DESCRIPTION
**         x               - The input data value.
**     Returns     :
**         ---             - The function returns the result of the
**                           (Arctan x) / pi calculation. This result
**                           represents the angle in radians whose
**                           tangent is x, divided by pi.
** ===================================================================
*/

#define TFR1_tfr16Atan2OverPI(y, x) tfr16Atan2OverPI(y, x)
/*
** ===================================================================
**     Method      :  TFR1_tfr16Atan2OverPI (component DSP_Func_TFR)
**
**     Description :
**         The function calculates the Arctan (y / x), and divides
**         that result by pi; i.e., (Arctan (y / x)) / pi
**     Parameters  :
**         NAME            - DESCRIPTION
**         y               - The first input data value.
**         x               - The second input data value.
**     Returns     :
**         ---             - The function returns result of the
**                           (Arctan (y / x)) / pi calculation.
** ===================================================================
*/

#define TFR1_tfr16SineWaveGenIDTL(pSWG, pValues, Nsamples) tfr16SineWaveGenIDTL(pSWG, pValues, Nsamples)
/*
** ===================================================================
**     Method      :  TFR1_tfr16SineWaveGenIDTL (component DSP_Func_TFR)
**
**     Description :
**         The function generates Nsamples and stores them in
**         pValues.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pSWG            - Pointer to tfr16_SineWaveGenIDTL type
**                           defined in tfr16.h header file. It
**                           points to private data for the IDTL sine
**                           wave generation function.
**       * pValues         - A pointer to memory allocated
**                           by the application to store sine samples.
**         Nsamples        - The number of sine samples to
**                           generate.
**     Returns     : Nothing
** ===================================================================
*/

#define TFR1_tfr16SineWaveGenIDTLCreate(pSineTable, SineTableLength, SineFreq, SampleFreq, InitialPhasePIx) tfr16SineWaveGenIDTLCreate(pSineTable, SineTableLength, SineFreq, SampleFreq, InitialPhasePIx)
/*
** ===================================================================
**     Method      :  TFR1_tfr16SineWaveGenIDTLCreate (component DSP_Func_TFR)
**
**     Description :
**         The function allocates the structure of type
**         tfr16_tSineWaveGenIDTL. This method is enabled only if
**         Memory management property is enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pSineTable      - Pointer to a sine look-up
**                           table which is allocated and filled by the
**                           application.
**         SineTableLength - The length of the
**                           sine look-up table.
**         SineFreq        - The frequency of the sine wave
**                           to be generated.
**         SampleFreq      - The frequency to sample the
**                           sine wave.
**         InitialPhasePIx - The starting phase
**                           of the sine wave to be generated.
**     Returns     :
**         ---             - The function returns a pointer to the
**                           tfr16_tSineWaveGenIDTL structure, which is
**                           used by all other tfr16SineWaveGenIDTL
**                           functions.
** ===================================================================
*/

#define TFR1_tfr16SineWaveGenIDTLDestroy(pSWG) tfr16SineWaveGenIDTLDestroy(pSWG)
/*
** ===================================================================
**     Method      :  TFR1_tfr16SineWaveGenIDTLDestroy (component DSP_Func_TFR)
**
**     Description :
**         The function frees the tfr16_tSineWaveGenIDTL data
**         structures(s) previously allocated by
**         tfr16SineWaveGenIDTLCreate. This method is enabled only if
**         Memory management property is enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pSWG            - Pointer to tfr16_SineWaveGenIDTL type
**                           defined in tfr16.h header file. It points
**                           to private data for the IDTL sine wave
**                           generation function.
**     Returns     : Nothing
** ===================================================================
*/

#define TFR1_tfr16SineWaveGenIDTLInit(pSWG, pSineTable, SineTableLength, SineFreq, SampleFreq, InitialPhasePIx) tfr16SineWaveGenIDTLInit(pSWG, pSineTable, SineTableLength, SineFreq, SampleFreq, InitialPhasePIx)
/*
** ===================================================================
**     Method      :  TFR1_tfr16SineWaveGenIDTLInit (component DSP_Func_TFR)
**
**     Description :
**         The function initializes the tfr16_tSineWaveGenIDTL data
**         structure used by all tfr16SineWaveGenIDTL functions. The
**         tfr16_tSineWaveGenIDTL data structure pointed to by pSWG
**         must have been allocated prior to calling
**         tfr16SineWaveGenIDTLInit.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pSWG            - Pointer to tfr16_SineWaveGenIDTL type
**                           defined in tfr16.h header file. It
**                           points to private data for the IDTL sine
**                           wave generation function.
**       * pSineTable      - Pointer to a sine look-up
**                           table which is allocated and filled by
**                           the application.
**         SineTableLength - The length of
**                           the sine look-up table.
**         SineFreq        - The frequency of the sine
**                           wave to be generated.
**         SampleFreq      - The frequency to sample
**                           the sine wave.
**         InitialPhasePIx - The starting
**                           phase of the sine wave to be generated.
**     Returns     : Nothing
** ===================================================================
*/

#define TFR1_tfr16SineWaveGenRDTL(pSWG, pValues, Nsamples) tfr16SineWaveGenRDTL(pSWG, pValues, Nsamples)
/*
** ===================================================================
**     Method      :  TFR1_tfr16SineWaveGenRDTL (component DSP_Func_TFR)
**
**     Description :
**         The function generates Nsamples and stores them in
**         pValues.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pSWG            - Pointer to tfr16_SineWaveGenRDTL type
**                           defined in tfr16.h header file. It
**                           points to private data for the RDTL sine
**                           wave generation function.
**       * pValues         - A pointer to memory allocated
**                           by the application to store sine samples.
**         Nsamples        - The number of sine samples to
**                           generate.
**     Returns     : Nothing
** ===================================================================
*/

#define TFR1_tfr16SineWaveGenRDTLCreate(pSineTable, SineTableLength, SineFreq, SampleFreq, InitialPhasePIx) tfr16SineWaveGenRDTLCreate(pSineTable, SineTableLength, SineFreq, SampleFreq, InitialPhasePIx)
/*
** ===================================================================
**     Method      :  TFR1_tfr16SineWaveGenRDTLCreate (component DSP_Func_TFR)
**
**     Description :
**         The function allocates the structure of type
**         tfr16_tSineWaveGenRDTL. This method is enabled only if
**         Memory management property is enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pSineTable      - Pointer to a sine look-up
**                           table which is allocated and filled by the
**                           application.
**         SineTableLength - The length of the
**                           sine look-up table.
**         SineFreq        - The frequency of the sine wave
**                           to be gen-erated.
**         SampleFreq      - The frequency to sample the
**                           sine wave.
**         InitialPhasePIx - The starting phase
**                           of the sine wave to be generated.
**     Returns     :
**         ---             - The function returns a pointer to the
**                           tfr16_tSineWaveGenRDTL structure, which is
**                           used by all other tfr16SineWaveGenRDTL
**                           functions.
** ===================================================================
*/

#define TFR1_tfr16SineWaveGenRDTLDestroy(pSWG) tfr16SineWaveGenRDTLDestroy(pSWG)
/*
** ===================================================================
**     Method      :  TFR1_tfr16SineWaveGenRDTLDestroy (component DSP_Func_TFR)
**
**     Description :
**         The function frees the tfr16_tSineWaveGenRDTL data
**         structures(s) previously allocated by
**         tfr16SineWaveGenRDTLCreate. This method is enabled only if
**         Memory management property is enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pSWG            - Pointer to tfr16_SineWaveGenRDTL type
**                           defined in tfr16.h header file. It points
**                           to private data for the RDTL sine wave
**                           generation function.
**     Returns     : Nothing
** ===================================================================
*/

#define TFR1_tfr16SineWaveGenRDTLInit(pSWG, pSineTable, SineTableLength, SineFreq, SampleFreq, InitialPhasePIx) tfr16SineWaveGenRDTLInit(pSWG, pSineTable, SineTableLength, SineFreq, SampleFreq, InitialPhasePIx)
/*
** ===================================================================
**     Method      :  TFR1_tfr16SineWaveGenRDTLInit (component DSP_Func_TFR)
**
**     Description :
**         The function initializes the tfr16_tSineWaveGenRDTL data
**         structure used by all tfr16SineWaveGenRDTL functions. The
**         tfr16_tSineWaveGenRDTL data structure pointed to by pSWG
**         must have been allocated prior to calling
**         tfr16SineWaveGenRDTLInit.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pSWG            - Pointer to tfr16_SineWaveGenRDTL type
**                           defined in tfr16.h header file. It
**                           points to private data for the RDTL sine
**                           wave generation function.
**       * pSineTable      - Pointer to a sine look-up
**                           table which is allocated and filled by
**                           the application.
**         SineTableLength - The length of
**                           the sine look-up table.
**         SineFreq        - The frequency of the sine
**                           wave to be gen-erated.
**         SampleFreq      - The frequency to sample
**                           the sine wave.
**         InitialPhasePIx - The starting
**                           phase of the sine wave to be generated.
**     Returns     : Nothing
** ===================================================================
*/

#define TFR1_tfr16SineWaveGenRDITL(pSWG, pValues, Nsamples) tfr16SineWaveGenRDITL(pSWG, pValues, Nsamples)
/*
** ===================================================================
**     Method      :  TFR1_tfr16SineWaveGenRDITL (component DSP_Func_TFR)
**
**     Description :
**         The function generates Nsamples and stores them in
**         pValues.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pSWG            - Pointer to tfr16_SineWaveGenRDITL
**                           type defined in tfr16.h header file. It
**                           points to private data for the RDITL
**                           sine wave generation function.
**       * pValues         - A pointer to memory allocated
**                           by the application to store sine samples.
**         Nsamples        - The number of sine samples to
**                           generate.
**     Returns     : Nothing
** ===================================================================
*/

#define TFR1_tfr16SineWaveGenRDITLCreate(pSineTable, SineTableLength, SineFreq, SampleFreq, InitialPhasePIx) tfr16SineWaveGenRDITLCreate(pSineTable, SineTableLength, SineFreq, SampleFreq, InitialPhasePIx)
/*
** ===================================================================
**     Method      :  TFR1_tfr16SineWaveGenRDITLCreate (component DSP_Func_TFR)
**
**     Description :
**         The function allocates the structure of type
**         tfr16_tSineWaveGenRDITL. This method is enabled only if
**         Memory management property is enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pSineTable      - Pointer to a sine look-up
**                           table which is allocated and filled by the
**                           application.
**         SineTableLength - The length of the
**                           sine look-up table.
**         SineFreq        - The frequency of the sine wave
**                           to be generated.
**         SampleFreq      - The frequency to sample the
**                           sine wave.
**         InitialPhasePIx - The starting phase
**                           of the sine wave to be generated.
**     Returns     :
**         ---             - The function returns a pointer to the
**                           tfr16_tSineWaveGenRDITL structure, which is
**                           used by all other tfr16SineWaveGenRDITL
**                           functions.
** ===================================================================
*/

#define TFR1_tfr16SineWaveGenRDITLDestroy(pSWG) tfr16SineWaveGenRDITLDestroy(pSWG)
/*
** ===================================================================
**     Method      :  TFR1_tfr16SineWaveGenRDITLDestroy (component DSP_Func_TFR)
**
**     Description :
**         The function frees the tfr16_tSineWaveGenRDITL data
**         structures(s) previously allocated by
**         tfr16SineWaveGenRDITLCreate. This method is enabled only if
**         Memory management property is enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pSWG            - Pointer to tfr16_SineWaveGenRDITL type
**                           defined in tfr16.h header file. It points
**                           to private data for the RDITL sine wave
**                           generation function.
**     Returns     : Nothing
** ===================================================================
*/

#define TFR1_tfr16SineWaveGenRDITLInit(pSWG, pSineTable, SineTableLength, SineFreq, SampleFreq, InitialPhasePIx) tfr16SineWaveGenRDITLInit(pSWG, pSineTable, SineTableLength, SineFreq, SampleFreq, InitialPhasePIx)
/*
** ===================================================================
**     Method      :  TFR1_tfr16SineWaveGenRDITLInit (component DSP_Func_TFR)
**
**     Description :
**         The function initializes the tfr16_tSineWaveGenRDITL data
**         structure used by all tfr16SineWaveGenRDITL functions.
**         The tfr16_tSineWaveGenRDITL data structure pointed to by
**         pSWG must have been allocated prior to calling
**         tfr16SineWaveGenRDITLInit.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pSWG            - Pointer to tfr16_SineWaveGenRDITL
**                           type defined in tfr16.h header file. It
**                           points to private data for the RDITL
**                           sine wave generation function.
**       * pSineTable      - Pointer to a sine look-up
**                           table which is allocated and filled by
**                           the application.
**         SineTableLength - The length of
**                           the sine look-up table.
**         SineFreq        - The frequency of the sine
**                           wave to be generated.
**         SampleFreq      - The frequency to sample
**                           the sine wave.
**         InitialPhasePIx - The starting
**                           phase of the sine wave to be generated.
**     Returns     : Nothing
** ===================================================================
*/

#define TFR1_tfr16SineWaveGenRDITLQ(pSWG, pValues, Nsamples) tfr16SineWaveGenRDITLQ(pSWG, pValues, Nsamples)
/*
** ===================================================================
**     Method      :  TFR1_tfr16SineWaveGenRDITLQ (component DSP_Func_TFR)
**
**     Description :
**         The function generates Nsamples and stores them in
**         pValues.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pSWG            - Pointer to tfr16_SineWaveGenRDITLQ
**                           type defined in tfr16.h header file. It
**                           points to private data for the RDITL
**                           sine wave generation function.
**       * pValues         - A pointer to memory allocated
**                           by the application to store sine samples.
**         Nsamples        - The number of sine samples to
**                           generate.
**     Returns     : Nothing
** ===================================================================
*/

#define TFR1_tfr16SineWaveGenRDITLQCreate(pSineTable, SineTableLength, SineFreq, SampleFreq, InitialPhasePIx) tfr16SineWaveGenRDITLQCreate(pSineTable, SineTableLength, SineFreq, SampleFreq, InitialPhasePIx)
/*
** ===================================================================
**     Method      :  TFR1_tfr16SineWaveGenRDITLQCreate (component DSP_Func_TFR)
**
**     Description :
**         The function allocates the structure of type
**         tfr16_tSineWaveGenRDITLQ. This method is enabled only if
**         Memory management property is enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pSineTable      - Pointer to a sine look-up
**                           table which is allocated and filled by the
**                           application.
**         SineTableLength - The length of the
**                           sine look-up table.
**         SineFreq        - The frequency of the sine wave
**                           to be generated.
**         SampleFreq      - The frequency to sample the
**                           sine wave.
**         InitialPhasePIx - The starting phase
**                           of the sine wave to be generated.
**     Returns     :
**         ---             - The function returns a pointer to the
**                           tfr16_tSineWaveGenRDITLQ structure, which
**                           is used by all other tfr16SineWaveGenRDITLQ
**                           functions.
** ===================================================================
*/

#define TFR1_tfr16SineWaveGenRDITLQDestroy(pSWG) tfr16SineWaveGenRDITLQDestroy(pSWG)
/*
** ===================================================================
**     Method      :  TFR1_tfr16SineWaveGenRDITLQDestroy (component DSP_Func_TFR)
**
**     Description :
**         The function frees the tfr16_tSineWaveGenRDITLQ data
**         structures(s) previously allocated by
**         tfr16SineWaveGenRDITLQCreate. This method is enabled only if
**         Memory management property is enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pSWG            - Pointer to tfr16_SineWaveGenRDITLQ type
**                           defined in tfr16.h header file. It points
**                           to private data for the RDITL sine wave
**                           generation function.
**     Returns     : Nothing
** ===================================================================
*/

#define TFR1_tfr16SineWaveGenRDITLQInit(pSWG, pSineTable, SineTableLength, SineFreq, SampleFreq, InitialPhasePIx) tfr16SineWaveGenRDITLQInit(pSWG, pSineTable, SineTableLength, SineFreq, SampleFreq, InitialPhasePIx)
/*
** ===================================================================
**     Method      :  TFR1_tfr16SineWaveGenRDITLQInit (component DSP_Func_TFR)
**
**     Description :
**         The function initializes the tfr16_tSineWaveGenRDITLQ
**         data structure used by all tfr16SineWaveGenRDITLQ
**         functions. The tfr16_tSineWaveGenRDITLQ data structure
**         pointed to by pSWG must have been allocated prior to
**         calling tfr16SineWaveGenRDITLQInit.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pSWG            - Pointer to tfr16_SineWaveGenRDITLQ
**                           type defined in tfr16.h header file. It
**                           points to private data for the RDITL
**                           sine wave generation function.
**       * pSineTable      - Pointer to a sine look-up
**                           table which is allocated and filled by
**                           the application.
**         SineTableLength - The length of
**                           the sine look-up table.
**         SineFreq        - The frequency of the sine
**                           wave to be generated.
**         SampleFreq      - The frequency to sample
**                           the sine wave.
**         InitialPhasePIx - The starting
**                           phase of the sine wave to be generated.
**     Returns     : Nothing
** ===================================================================
*/

#define TFR1_tfr16SineWaveGenPAM(pSWG, pValues, Nsamples) tfr16SineWaveGenPAM(pSWG, pValues, Nsamples)
/*
** ===================================================================
**     Method      :  TFR1_tfr16SineWaveGenPAM (component DSP_Func_TFR)
**
**     Description :
**         The function generates Nsamples and stores them in
**         pValues.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pSWG            - Pointer to tfr16_SineWaveGenPAM type
**                           defined in tfr16.h header file. It
**                           points to private data for the PAM sine
**                           wave generation function.
**       * pValues         - A pointer to memory allocated
**                           by the application to store sine samples.
**         Nsamples        - The number of sine samples to
**                           generate.
**     Returns     : Nothing
** ===================================================================
*/

#define TFR1_tfr16SineWaveGenPAMCreate(SineFreq, SampleFreq, InitialPhasePIx, Amplitude) tfr16SineWaveGenPAMCreate(SineFreq, SampleFreq, InitialPhasePIx, Amplitude)
/*
** ===================================================================
**     Method      :  TFR1_tfr16SineWaveGenPAMCreate (component DSP_Func_TFR)
**
**     Description :
**         The function allocates the structure of type
**         tfr16_SineWaveGenPAM. This method is enabled only if Memory
**         management property is enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**         SineFreq        - The frequency of the sine wave
**                           to be generated.
**         SampleFreq      - The frequency to sample the
**                           sine wave.
**         InitialPhasePIx - The starting phase
**                           of the sine wave to be generated.
**         Amplitude       - A scaling factor of the
**                           generated sine wave.
**     Returns     :
**         ---             - The function returns a pointer to the
**                           tfr16_tSineWaveGenPAM structure, which is
**                           used by all other tfr16SineWaveGenPAM
**                           functions.
** ===================================================================
*/

#define TFR1_tfr16SineWaveGenPAMDestroy(pSWG) tfr16SineWaveGenPAMDestroy(pSWG)
/*
** ===================================================================
**     Method      :  TFR1_tfr16SineWaveGenPAMDestroy (component DSP_Func_TFR)
**
**     Description :
**         The function frees the tfr16_tSineWaveGenPAM data
**         structures(s) previously allocated by
**         tfr16SineWaveGenPAMCreate. This method is enabled only if
**         Memory management property is enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pSWG            - Pointer to tfr16_SineWaveGenPAM type
**                           defined in tfr16.h header file. It points
**                           to private data for the PAM sine wave
**                           generation function.
**     Returns     : Nothing
** ===================================================================
*/

#define TFR1_tfr16SineWaveGenPAMInit(pSWG, SineFreq, SampleFreq, InitialPhasePIx, Amplitude) tfr16SineWaveGenPAMInit(pSWG, SineFreq, SampleFreq, InitialPhasePIx, Amplitude)
/*
** ===================================================================
**     Method      :  TFR1_tfr16SineWaveGenPAMInit (component DSP_Func_TFR)
**
**     Description :
**         The function initializes the tfr16_tSineWaveGenPAM data
**         structure used by all tfr16SineWaveGenPAM functions. The
**         tfr16_tSineWaveGenPAM data structure pointed to by pSWG
**         must have been allocated prior to calling
**         tfr16SineWaveGenPAMInit.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pSWG            - Pointer to tfr16_SineWaveGenPAM type
**                           defined in tfr16.h header file. It
**                           points to private data for the PAM sine
**                           wave generation function.
**         SineFreq        - The frequency of the sine
**                           wave to be generated.
**         SampleFreq      - The frequency to sample
**                           the sine wave.
**         InitialPhasePIx - The starting
**                           phase of the sine wave to be generated.
**         Amplitude       - A scaling factor of the
**                           generated sine wave.
**     Returns     : Nothing
** ===================================================================
*/

#define TFR1_tfr16SineWaveGenDOM(pSWG, pValues, Nsamples) tfr16SineWaveGenDOM(pSWG, pValues, Nsamples)
/*
** ===================================================================
**     Method      :  TFR1_tfr16SineWaveGenDOM (component DSP_Func_TFR)
**
**     Description :
**         The function generates Nsamples and stores them in
**         pValues.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pSWG            - Pointer to tfr16_SineWaveGenDOM type
**                           defined in tfr16.h header file. It
**                           points to private data for the DOM sine
**                           wave generation function.
**       * pValues         - A pointer to memory allocated
**                           by the application to store sine samples.
**         Nsamples        - The number of sine samples to
**                           generate.
**     Returns     : Nothing
** ===================================================================
*/

#define TFR1_tfr16SineWaveGenDOMCreate(SineFreq, SampleFreq, InitialPhasePIx, Amplitude) tfr16SineWaveGenDOMCreate(SineFreq, SampleFreq, InitialPhasePIx, Amplitude)
/*
** ===================================================================
**     Method      :  TFR1_tfr16SineWaveGenDOMCreate (component DSP_Func_TFR)
**
**     Description :
**         The function allocates the structure of type
**         tfr16_tSineWaveGenPAM. This method is enabled only if Memory
**         management property is enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**         SineFreq        - The frequency of the sine wave
**                           to be generated.
**         SampleFreq      - The frequency to sample the
**                           sine wave.
**         InitialPhasePIx - The starting phase
**                           of the sine wave to be generated.
**         Amplitude       - A scaling factor of the
**                           generated sine wave.
**     Returns     :
**         ---             - The function returns a pointer to the
**                           tfr16_tSineWaveGenPAM structure, which is
**                           used by all other tfr16SineWaveGenDOM
**                           functions.
** ===================================================================
*/

#define TFR1_tfr16SineWaveGenDOMDestroy(pSWG) tfr16SineWaveGenDOMDestroy(pSWG)
/*
** ===================================================================
**     Method      :  TFR1_tfr16SineWaveGenDOMDestroy (component DSP_Func_TFR)
**
**     Description :
**         The function frees the tfr16_tSineWaveGenPAM data
**         structures(s) previously allocated by
**         tfr16SineWaveGenPAMCreate. This method is enabled only if
**         Memory management property is enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pSWG            - Pointer to tfr16_SineWaveGenDOM type
**                           defined in tfr16.h header file. It points
**                           to private data for the DOM sine wave
**                           generation function.
**     Returns     : Nothing
** ===================================================================
*/

#define TFR1_tfr16SineWaveGenDOMInit(pSWG, SineFreq, SampleFreq, InitialPhasePIx, Amplitude) tfr16SineWaveGenDOMInit(pSWG, SineFreq, SampleFreq, InitialPhasePIx, Amplitude)
/*
** ===================================================================
**     Method      :  TFR1_tfr16SineWaveGenDOMInit (component DSP_Func_TFR)
**
**     Description :
**         The function initializes the tfr16_tSineWaveGenPAM data
**         structure used by all tfr16SineWaveGenDOM functions. The
**         tfr16_tSineWaveGenPAM data structure pointed to by pSWG
**         must have been allocated prior to calling
**         tfr16SineWaveGenDOMInit.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pSWG            - Pointer to tfr16_SineWaveGenDOM type
**                           defined in tfr16.h header file. It
**                           points to private data for the DOM sine
**                           wave generation function.
**         SineFreq        - The frequency of the sine
**                           wave to be generated
**         SampleFreq      - The frequency to sample
**                           the sine wave.
**         InitialPhasePIx - The starting
**                           phase of the sine wave to be generated.
**         Amplitude       - A scaling factor of the
**                           generated sine wave.
**     Returns     : Nothing
** ===================================================================
*/

#define TFR1_tfr16WaveGenRDITLQ(pSWG, PhaseIncrement) tfr16WaveGenRDITLQ(pSWG, PhaseIncrement)
/*
** ===================================================================
**     Method      :  TFR1_tfr16WaveGenRDITLQ (component DSP_Func_TFR)
**
**     Description :
**         The function generates one sample and returns it.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pSWG            - Pointer to tfr16_WaveGenRDITLQ type
**                           defined in tfr16.h header file. It
**                           points to private data for the RDITLQ
**                           wave generation function.
**         PhaseIncrement  - The value to
**                           increment/decrement the phase by -1
**                           period to 1 period.
**     Returns     :
**         ---             - The function returns one sample.
** ===================================================================
*/

#define TFR1_tfr16WaveGenRDITLQCreate(pSineTable, SineTableLength, InitialPhasePIx) tfr16WaveGenRDITLQCreate(pSineTable, SineTableLength, InitialPhasePIx)
/*
** ===================================================================
**     Method      :  TFR1_tfr16WaveGenRDITLQCreate (component DSP_Func_TFR)
**
**     Description :
**         The function allocates the structure of type
**         tfr16_tWaveGenRDITLQ. This method is enabled only if Memory
**         management property is enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pSineTable      - Pointer to a sine look-up
**                           table which is allocated and filled by the
**                           application.
**         SineTableLength - The length of the
**                           sine look-up table.
**         InitialPhasePIx - The starting phase
**                           of the sine wave to be generated.
**     Returns     :
**         ---             - The function returns a pointer to the
**                           tfr16_tWaveGenRDITLQ structure, which is
**                           used by all other tfr16WaveGenRDITLQ
**                           functions.
** ===================================================================
*/

#define TFR1_tfr16WaveGenRDITLQDestroy(pSWG) tfr16WaveGenRDITLQDestroy(pSWG)
/*
** ===================================================================
**     Method      :  TFR1_tfr16WaveGenRDITLQDestroy (component DSP_Func_TFR)
**
**     Description :
**         The function frees the tfr16_tWaveGenRDITLQ data
**         structures(s) previously allocated by
**         tfr16WaveGenRDITLQCreate. This method is enabled only if
**         Memory management property is enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pSWG            - Pointer to tfr16_WaveGenRDITLQ type
**                           defined in tfr16.h header file. It points
**                           to private data for the RDITLQ wave
**                           generation function.
**     Returns     : Nothing
** ===================================================================
*/

#define TFR1_tfr16WaveGenRDITLQInit(pSWG, pSineTable, SineTableLength, InitialPhasePIx) tfr16WaveGenRDITLQInit(pSWG, pSineTable, SineTableLength, InitialPhasePIx)
/*
** ===================================================================
**     Method      :  TFR1_tfr16WaveGenRDITLQInit (component DSP_Func_TFR)
**
**     Description :
**         The function initializes the tfr16_tWaveGenRDITLQ data
**         structure used by all tfr16WaveGenRDITLQ functions. The
**         tfr16_tWaveGenRDITLQ data structure pointed to by pSWG
**         must have been allocated prior to calling
**         tfr16WaveGenRDITLQInit.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pSWG            - Pointer to tfr16_WaveGenRDITLQ type
**                           defined in tfr16.h header file. It
**                           points to private data for the RDITLQ
**                           wave generation function.
**       * pSineTable      - Pointer to a sine look-up
**                           table which is allocated and filled by
**                           the application.
**         SineTableLength - The length of
**                           the sine look-up table.
**         InitialPhasePIx - The starting
**                           phase of the sine wave to be generated.
**     Returns     : Nothing
** ===================================================================
*/

/* END TFR1. */

#endif /* ifndef __TFR1 */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.00 [04.35]
**     for the Freescale 56800 series of microcontrollers.
**
** ###################################################################
*/
