/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : VFR1.H
**     Project   : TP1
**     Processor : 56F8367
**     Component : DSP_Func_VFR
**     Version   : Component 01.013, Driver 01.05, CPU db: 2.87.058
**     Compiler  : Metrowerks DSP C Compiler
**     Date/Time : 30/07/2015, 19:47
**     Abstract  :
**          This bean implements several mathematical functions for vectors
**          of fractional types. These vector functions offer highly optimized
**          code for each operation to provide the best performance.
**          The function library provides such vector functions for the 16-bit (short),
**          fractional type. For portability, we have defined a short 16-bit fractional
**          type as Frac16. The vector functions include:
**             • addition
**             • dot product
**             • equality
**             • length
**             • multiplication
**             • scaling
**             • subtraction
**     Settings  :
**          Bean Name                      : VFR1
**          Use Assembler Files            : yes
**          Array Library                  : AFR1
**     Contents  :
**         vfr16Add     - void VFR1_vfr16Add(Frac16 *pX, Frac16 *pY, Frac16 *pZ, UInt16 n);
**         vfr16DotProd - Frac32 VFR1_vfr16DotProd(Frac16 *pX, Frac16 *pY, UInt16 n);
**         vfr16Equal   - bool VFR1_vfr16Equal(Frac16 *pX, Frac16 *pY, UInt16 n);
**         vfr16Length  - Frac16 VFR1_vfr16Length(Frac16 *pX, UInt16 n);
**         vfr16Mult    - void VFR1_vfr16Mult(Frac16 c, Frac16 *pX, Frac16 *pZ, UInt16 n);
**         vfr16Scale   - void VFR1_vfr16Scale(Int16 k, Frac16 *pX, Frac16 *pZ, UInt16 n);
**         vfr16Sub     - void VFR1_vfr16Sub(Frac16 *pX, Frac16 *pY, Frac16 *pZ, UInt16 n);
**
**     (c) Freescale Semiconductor
**     2004 All Rights Reserved
**
**     Copyright : 1997 - 2009 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef __VFR1
#define __VFR1

/* MODULE VFR1. */

/*Include shared modules, which are used for whole project*/
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited beans */
#include "AFR1.h"
#include "assert.h"
#include "dspfunc.h"

#include "Cpu.h"



#define vfr16Add(pX, pY, pZ, n) afr16Add(pX, pY, pZ, n)
#define VFR1_vfr16Add(pX, pY, pZ, n) afr16Add(pX, pY, pZ, n)
/*
** ===================================================================
**     Method      :  VFR1_vfr16Add (component DSP_Func_VFR)
**
**     Description :
**         The function totals two vectors; i.e., Z = X + Y. The
**         actual implementation adds each element of the two input
**         vectors, pZ[i] = pX[i] + pY[i], 0 <= i < n.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pX              - Pointer to the first input vector of
**                           fractional data values.
**       * pY              - Pointer to the second input vector of
**                           fractional data values.
**       * pZ              - Pointer to the output vector of
**                           fractional results.
**         n               - The number of elements in all input and
**                           output vectors.
**     Returns     : Nothing
** ===================================================================
*/

#define VFR1_vfr16DotProd(pX, pY, n) vfr16DotProd(pX, pY, n)
Frac32 vfr16DotProd(Frac16 *pX,Frac16 *pY,UInt16 n);
/*
** ===================================================================
**     Method      :  VFR1_vfr16DotProd (component DSP_Func_VFR)
**
**     Description :
**         The function calculates the dot product of two input
**         vectors.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pX              - Pointer to the first input vector.
**       * pY              - Pointer to the second input vector.
**         n               - The number of elements in both input
**                           vectors.
**     Returns     :
**         ---             - The function returns the 32-bit
**                           fractional result of the dot product (X
**                           · Y) operation.
** ===================================================================
*/

#define vfr16Equal(pX, pY, n) afr16Equal(pX, pY, n)
#define VFR1_vfr16Equal(pX, pY, n) afr16Equal(pX, pY, n)
/*
** ===================================================================
**     Method      :  VFR1_vfr16Equal (component DSP_Func_VFR)
**
**     Description :
**         The function tests two vectors for equality; i.e., X == Y;
**         the actual implementation tests each corresponding
**         element, pX[i] == pY[i], 0 <= i < n.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pX              - Pointer to an input vector X of
**                           fractional data values.
**       * pY              - Pointer to an input vector Y of
**                           fractional data values.
**         n               - The number of elements in the input
**                           vectors.
**     Returns     :
**         ---             - The function returns true if two
**                           vectors are equal; otherwise, equal
**                           returns false.
** ===================================================================
*/

#define VFR1_vfr16Length(pX, n) vfr16Length(pX, n)
Frac16 vfr16Length(Frac16 *pX,UInt16 n);
/*
** ===================================================================
**     Method      :  VFR1_vfr16Length (component DSP_Func_VFR)
**
**     Description :
**         The function calculates the length, or amplitude, of the
**         input vector.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pX              - Pointer to the input vector of fractional
**                           data values.
**         n               - The number of elements in the input
**                           vector.
**     Returns     :
**         ---             - The function returns the length of the
**                           input vector.
** ===================================================================
*/

#define VFR1_vfr16Mult(c, pX, pZ, n) vfr16Mult(c, pX, pZ, n)
void vfr16Mult(Frac16 c,Frac16 *pX,Frac16 *pZ,UInt16 n);
/*
** ===================================================================
**     Method      :  VFR1_vfr16Mult (component DSP_Func_VFR)
**
**     Description :
**         The function multiplies an input vector by a fractional
**         constant; i.e., Z = cX. The actual calculation multiplies
**         the constant c by each of the elements of the vector, i.e.,
**         pZ[i] = c * pX[i], 0 <= i < n.
**     Parameters  :
**         NAME            - DESCRIPTION
**         c               - A fractional value to multiply the input
**                           vector.
**       * pX              - Pointer to the input vector.
**       * pZ              - Pointer to the output vector.
**         n               - The number of elements in the input and
**                           output vectors.
**     Returns     : Nothing
** ===================================================================
*/

#define VFR1_vfr16Scale(k, pX, pZ, n) vfr16Scale(k, pX, pZ, n)
void vfr16Scale(Int16 k,Frac16 *pX,Frac16 *pZ,UInt16 n);
/*
** ===================================================================
**     Method      :  VFR1_vfr16Scale (component DSP_Func_VFR)
**
**     Description :
**         The function multiplies an input vector by an unsigned
**         integer constant; i.e., Z = kX. The actual calculation
**         multiplies the constant k by each of the elements of the
**         vector; i.e., pZ[i] = k * pX[i], 0 <= i < n.
**     Parameters  :
**         NAME            - DESCRIPTION
**         k               - An unsigned, integer value with which to
**                           scale the input vector.
**       * pX              - Pointer to the input vector.
**       * pZ              - Pointer to the output vector.
**         n               - The number of elements in the input and
**                           output vectors.
**     Returns     : Nothing
** ===================================================================
*/

#define vfr16Sub(pX, pY, pZ, n) afr16Sub(pX, pY, pZ, n)
#define VFR1_vfr16Sub(pX, pY, pZ, n) afr16Sub(pX, pY, pZ, n)
/*
** ===================================================================
**     Method      :  VFR1_vfr16Sub (component DSP_Func_VFR)
**
**     Description :
**         The function provides a vector subtraction operation; i.e.,
**         Z = X - Y; the actual calculation subtracts each
**         corresponding element, pZ[i] = pX[i] - pY[i], 0 <= i < n.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * pX              - Pointer to the first input vector of
**                           fractional data values.
**       * pY              - Pointer to the second input vector of
**                           fractional data values.
**       * pZ              - Pointer to the output vector of
**                           fractional results.
**         n               - The length of all input and output
**                           vectors.
**     Returns     : Nothing
** ===================================================================
*/

/* END VFR1. */

#endif /* ifndef __VFR1 */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.00 [04.35]
**     for the Freescale 56800 series of microcontrollers.
**
** ###################################################################
*/
